feed2js_ck = true;


		var headID = document.getElementsByTagName("head")[0];         
		var cssNode = document.createElement('link');
		cssNode.type = 'text/css';
		cssNode.rel = 'stylesheet';
		cssNode.href = 'https://weightlessbooks.com/feed2js/style/weightless.css';
		cssNode.media = 'screen';
		headID.appendChild(cssNode);
	
document.write('<div class="rss-box">');
document.write('<p class="rss-title"><a class="rss-title" href="https://weightlessbooks.com?ap_id=" target="_blank">Weightless Books</a><br /><span class="rss-item">(e)Books That Don\'t Weigh You Down</span></p>');
document.write('<ul class="rss-items">');
document.write('<li class="rss-item">');
document.write('<div><div class=\"cover\"><a href=\"https://weightlessbooks.com/genre/fiction/solitaire-a-novel/?ap_id=smallb\"><img width=\"75\" height=\"116\" src=\"http://weightlessbooks.com/wp-content/uploads/images/solitaire-a-novel-cover-75x116.gif\" class=\"attachment-sm size-sm wp-post-image\" alt=\"Solitaire: a novel\" title=\"Solitaire: a novel\" srcset=\"http://weightlessbooks.com/wp-content/uploads/images/solitaire-a-novel-cover-75x116.gif 75w, http://weightlessbooks.com/wp-content/uploads/images/solitaire-a-novel-cover-200x310.gif 200w, http://weightlessbooks.com/wp-content/uploads/images/solitaire-a-novel-cover-140x217.gif 140w\" sizes=\"(max-width: 75px) 100vw, 75px\" /></a><br><div class=\"buy_buttons\"><a href=\"https://weightlessbooks.com/genre/fiction/solitaire-a-novel/?ap_id=smallb\"><b>$6.99</b></a><br></div></div><h3><a href=\"https://weightlessbooks.com/genre/fiction/solitaire-a-novel/?ap_id=smallb\">Solitaire: a novel</a> Kelley Eskridge</h3><p><b>Soon to be a motion picture: <i><a href=\"https://www.facebook.com/OtherLife-Movie-1452884191706410/?ap_id=smallb\">OtherLife</a>.</i></b></p> <p>A <em>New York Times</em> Notable Book, Borders Original Voices selection, and Nebula, Endeavour, and Spectrum Award finalist.</p> <p>“A stylistic and psychological tour de force.”—… <a href=\"https://weightlessbooks.com/genre/fiction/solitaire-a-novel/?ap_id=smallb\" class=\"read-more\">More</a></p></div>');
document.write('</li>');
document.write('<li class="rss-item">');
document.write('<div><div class=\"cover\"><a href=\"https://weightlessbooks.com/format/ambiguity-machines/?ap_id=smallb\"><img width=\"75\" height=\"115\" src=\"http://weightlessbooks.com/wp-content/uploads/images/ambiguity-machines-cover-75x115.gif\" class=\"attachment-sm size-sm wp-post-image\" alt=\"Ambiguity Machines Preorder\" title=\"Ambiguity Machines Preorder\" srcset=\"http://weightlessbooks.com/wp-content/uploads/images/ambiguity-machines-cover-75x115.gif 75w, http://weightlessbooks.com/wp-content/uploads/images/ambiguity-machines-cover-200x307.gif 200w, http://weightlessbooks.com/wp-content/uploads/images/ambiguity-machines-cover-140x215.gif 140w\" sizes=\"(max-width: 75px) 100vw, 75px\" /></a><div class=\"preorder_label\">Release Date:<br>Feb 13th, 2018</div><br><div class=\"buy_buttons\"><a href=\"https://weightlessbooks.com/format/ambiguity-machines/?ap_id=smallb\"><b>$9.95</b></a><br></div></div><h3><a href=\"https://weightlessbooks.com/format/ambiguity-machines/?ap_id=smallb\">Ambiguity Machines Preorder</a> Vandana Singh</h3><p><em> A book of stories about the uncertainty with which we move through space and time, by ourselves and with others. <span id=\"more-15324\"></span></em></p> <p><strong>Read the title story:</strong> <a href=\"http://www.tor.com/2015/04/29/ambiguity-machines-an-examination-vandana-singh/?ap_id=smallb\"> Ambiguity Machines: An Examination</a></p> <p>In her first North American collection, Vandana… <a href=\"https://weightlessbooks.com/format/ambiguity-machines/?ap_id=smallb\" class=\"read-more\">More</a></p></div>');
document.write('</li>');
document.write('<li class="rss-item">');
document.write('<div><div class=\"cover\"><a href=\"https://weightlessbooks.com/format/telling-the-map/?ap_id=smallb\"><img width=\"75\" height=\"116\" src=\"http://weightlessbooks.com/wp-content/uploads/images/telling-the-map-cover-75x116.gif\" class=\"attachment-sm size-sm wp-post-image\" alt=\"Telling the Map\" title=\"Telling the Map\" srcset=\"http://weightlessbooks.com/wp-content/uploads/images/telling-the-map-cover-75x116.gif 75w, http://weightlessbooks.com/wp-content/uploads/images/telling-the-map-cover-200x309.gif 200w, http://weightlessbooks.com/wp-content/uploads/images/telling-the-map-cover-140x216.gif 140w\" sizes=\"(max-width: 75px) 100vw, 75px\" /></a><br><div class=\"buy_buttons\"><a href=\"https://weightlessbooks.com/format/telling-the-map/?ap_id=smallb\"><b>$9.95</b></a><br></div></div><h3><a href=\"https://weightlessbooks.com/format/telling-the-map/?ap_id=smallb\">Telling the Map</a> Christopher Rowe</h3><p><em>Stories that sometimes begin in the hills of Kentucky and head out into complicated and sometimes hopeful futures.<span id=\"more-14948\"></span></em></p> <p>“Precision was his watchword and his sacrament.”</p> <p>There are ten stories here including one readers… <a href=\"https://weightlessbooks.com/format/telling-the-map/?ap_id=smallb\" class=\"read-more\">More</a></p></div>');
document.write('</li>');
document.write('<li class="rss-item">');
document.write('<div><div class=\"cover\"><a href=\"https://weightlessbooks.com/format/the-river-bank/?ap_id=smallb\"><img width=\"75\" height=\"117\" src=\"http://weightlessbooks.com/wp-content/uploads/images/the-river-bank-cover-75x117.gif\" class=\"attachment-sm size-sm wp-post-image\" alt=\"The River Bank Preorder\" title=\"The River Bank Preorder\" srcset=\"http://weightlessbooks.com/wp-content/uploads/images/the-river-bank-cover-75x117.gif 75w, http://weightlessbooks.com/wp-content/uploads/images/the-river-bank-cover-200x312.gif 200w, http://weightlessbooks.com/wp-content/uploads/images/the-river-bank-cover-140x218.gif 140w\" sizes=\"(max-width: 75px) 100vw, 75px\" /></a><div class=\"preorder_label\">Release Date:<br>Sep 19th, 2017</div><br><div class=\"buy_buttons\"><a href=\"https://weightlessbooks.com/format/the-river-bank/?ap_id=smallb\"><b>$14.95</b></a><br></div></div><h3><a href=\"https://weightlessbooks.com/format/the-river-bank/?ap_id=smallb\">The River Bank Preorder</a> Kij Johnson</h3><p><em>A sequel to Kenneth Grahame’s The Wind in the Willows<span id=\"more-14947\"></span></em></p> <p>In this delightful dive into the bygone world of Kenneth Grahame’s <i>The Wind in the Willows</i> staunch Mole, sociable Water Rat, severe Badger, and troublesome and… <a href=\"https://weightlessbooks.com/format/the-river-bank/?ap_id=smallb\" class=\"read-more\">More</a></p></div>');
document.write('</li>');
document.write('<li class="rss-item">');
document.write('<div><div class=\"cover\"><a href=\"https://weightlessbooks.com/publisher/small-beer-press/big-mouth-house/in-other-lands/?ap_id=smallb\"><img width=\"75\" height=\"113\" src=\"http://weightlessbooks.com/wp-content/uploads/images/in-other-lands-cover-75x113.gif\" class=\"attachment-sm size-sm wp-post-image\" alt=\"In Other Lands Preorder\" title=\"In Other Lands Preorder\" srcset=\"http://weightlessbooks.com/wp-content/uploads/images/in-other-lands-cover-75x113.gif 75w, http://weightlessbooks.com/wp-content/uploads/images/in-other-lands-cover-200x301.gif 200w, http://weightlessbooks.com/wp-content/uploads/images/in-other-lands-cover-400x602.gif 400w, http://weightlessbooks.com/wp-content/uploads/images/in-other-lands-cover-140x211.gif 140w\" sizes=\"(max-width: 75px) 100vw, 75px\" /></a><div class=\"preorder_label\">Release Date:<br>Aug 15th, 2017</div><br><div class=\"buy_buttons\"><a href=\"https://weightlessbooks.com/publisher/small-beer-press/big-mouth-house/in-other-lands/?ap_id=smallb\"><b>$10.99</b></a><br></div></div><h3><a href=\"https://weightlessbooks.com/publisher/small-beer-press/big-mouth-house/in-other-lands/?ap_id=smallb\">In Other Lands Preorder</a> Sarah Rees Brennan</h3><p><em>Elliot doesn’t want to fight, keeps saying the wrong thing, and is definitely the grouchiest human in fantasyland.<span id=\"more-14958\"></span></em></p> <p>“The beauty of men is a sweet soft thing that passes all too soon, like a bird across the sky.”</p> <p>Sometimes… <a href=\"https://weightlessbooks.com/publisher/small-beer-press/big-mouth-house/in-other-lands/?ap_id=smallb\" class=\"read-more\">More</a></p></div>');
document.write('</li>');
document.write('</ul></div>');
